# c'est pas une variable que je définis moi-même, c'est toujours cette valeur pour les Deploymeents
apiVersion: apps/v1 

# on veut créer un objet de type Deployment
# un Deployment ça sert à quoi:
# - créer des pods et maintenir un nombre de pods donné
# - gérer les mises à jour de l'application
# - faire des rolling updates
kind: Deployment 

# metadata contient des informations pour identifier l'objet qu'on crée
metadata:
  name: jules-website # ça donne le nom jules-website au Deployment

# ! c'est la partie la plus importante, je définis ce que je veux que Kubernetes maintienne !
spec:
  replicas: 2 # je veux qu'il y ait 2 pods en permanence

  selector:
    matchLabels:
      app: jules-website # le déploiment considère que ses pods sont ceux ayant name=jules-website
  
  template:
    metadata:
      labels:
        app: jules-website
  
    spec:
      containers:
        - name: jules-website # nom que je donne au conteneur, c'est pas forcément le même nom que l'image docker
          image: jules-website:1.0 # nom de l'image Docker
          imagePullPolicy: IfNotPresent # ça permet de dire à Kind de ne pas re-télécharger l'image si elle est déjà présente sur le noeud
          ports:
            - containerPort: 80 # le PORC sur lequel le conteneur écoute
